[ids]
*

[main]
f23+leftshift+leftmeta = rightcontrol
leftshift+rightshift = capslock


# includes
include global
include enthium
include symbols
include qwerty
include mirror


# stuff, here tmp for order reasons
[enthium_shift+qwerty_control]
9 = 9
- = -
= = =

t = t

c = c
v = v
b = b